import type { Place, PlaceCategory } from '../../domain/places/place'

export type ExperienceCategory = 'anime' | 'technology' | 'shopping' | 'restaurant' | 'park'

export interface ExperienceTab {
  id: ExperienceCategory
  label: string
}

export const experienceTabs: ExperienceTab[] = [
  {
    id: 'anime',
    label: 'Anime',
  },
  {
    id: 'technology',
    label: 'Tecnologia',
  },
  {
    id: 'shopping',
    label: 'Compras',
  },
  {
    id: 'restaurant',
    label: 'Restaurantes',
  },
  {
    id: 'park',
    label: 'Disney & Universal',
  },
]

export const places: Place[] = [
  {
    id: 'pokemon-center-shibuya',
    name: 'Pokémon Center Shibuya',
    searchQuery: 'Pokemon Center Shibuya Tokyo Japan',
    city: 'Tokyo',
    district: 'Shibuya',
    category: 'anime',
    priority: 'must',
    estimatedBudgetJpy: 30000,
    estimatedDurationMinutes: 90,
    tags: ['pokemon', 'games', 'shopping', 'exclusive'],
    external: {},
  },
  {
    id: 'nintendo-tokyo',
    name: 'Nintendo Tokyo',
    searchQuery: 'Nintendo Tokyo Shibuya Japan',
    city: 'Tokyo',
    district: 'Shibuya',
    category: 'anime',
    priority: 'must',
    estimatedBudgetJpy: 25000,
    estimatedDurationMinutes: 75,
    tags: ['nintendo', 'games', 'shopping'],
    external: {},
  },
  {
    id: 'jump-shop-tokyo',
    name: 'Jump Shop',
    searchQuery: 'Jump Shop Tokyo Japan',
    city: 'Tokyo',
    category: 'anime',
    priority: 'high',
    estimatedBudgetJpy: 12000,
    estimatedDurationMinutes: 60,
    tags: ['manga', 'anime', 'shopping'],
    external: {},
  },
  {
    id: 'animate-ikebukuro',
    name: 'Animate Ikebukuro',
    searchQuery: 'Animate Ikebukuro Tokyo Japan',
    city: 'Tokyo',
    district: 'Ikebukuro',
    category: 'anime',
    priority: 'high',
    estimatedBudgetJpy: 15000,
    estimatedDurationMinutes: 120,
    tags: ['anime', 'manga', 'shopping'],
    external: {},
  },
  {
    id: 'mandarake-complex',
    name: 'Mandarake Complex',
    searchQuery: 'Mandarake Complex Akihabara Tokyo Japan',
    city: 'Tokyo',
    district: 'Akihabara',
    category: 'anime',
    priority: 'high',
    estimatedBudgetJpy: 15000,
    estimatedDurationMinutes: 90,
    tags: ['anime', 'manga', 'collectibles'],
    external: {},
  },
  {
    id: 'super-potato-akihabara',
    name: 'Super Potato',
    searchQuery: 'Super Potato Akihabara Tokyo Japan',
    city: 'Tokyo',
    district: 'Akihabara',
    category: 'anime',
    priority: 'must',
    estimatedBudgetJpy: 20000,
    estimatedDurationMinutes: 90,
    tags: ['retro-games', 'games', 'shopping'],
    external: {},
  },
  {
    id: 'ghibli-donguri-republic',
    name: 'Donguri Republic',
    searchQuery: 'Donguri Republic Tokyo Japan',
    city: 'Tokyo',
    category: 'anime',
    priority: 'high',
    estimatedBudgetJpy: 10000,
    estimatedDurationMinutes: 60,
    tags: ['ghibli', 'souvenirs', 'shopping'],
    external: {},
  },
  {
    id: 'yodobashi-akiba',
    name: 'Yodobashi Akiba',
    searchQuery: 'Yodobashi Akiba Tokyo Japan',
    city: 'Tokyo',
    district: 'Akihabara',
    category: 'technology',
    priority: 'must',
    estimatedBudgetJpy: 50000,
    estimatedDurationMinutes: 150,
    tags: ['electronics', 'camera', 'games'],
    external: {},
  },
  {
    id: 'bic-camera-yurakucho',
    name: 'Bic Camera',
    searchQuery: 'Bic Camera Yurakucho Tokyo Japan',
    city: 'Tokyo',
    district: 'Yurakucho',
    category: 'technology',
    priority: 'high',
    estimatedBudgetJpy: 40000,
    estimatedDurationMinutes: 120,
    tags: ['electronics', 'camera', 'shopping'],
    external: {},
  },
  {
    id: 'apple-marunouchi',
    name: 'Apple Marunouchi',
    searchQuery: 'Apple Marunouchi Tokyo Japan',
    city: 'Tokyo',
    district: 'Marunouchi',
    category: 'technology',
    priority: 'optional',
    estimatedDurationMinutes: 45,
    tags: ['apple', 'electronics'],
    external: {},
  },
  {
    id: 'don-quijote-shibuya',
    name: 'Mega Don Quijote Shibuya',
    searchQuery: 'MEGA Don Quijote Shibuya Tokyo Japan',
    city: 'Tokyo',
    district: 'Shibuya',
    category: 'shopping',
    priority: 'must',
    estimatedBudgetJpy: 25000,
    estimatedDurationMinutes: 120,
    tags: ['souvenirs', 'food', 'shopping'],
    external: {},
  },
  {
    id: 'muji-ginza',
    name: 'Muji Ginza',
    searchQuery: 'Muji Ginza Tokyo Japan',
    city: 'Tokyo',
    district: 'Ginza',
    category: 'shopping',
    priority: 'high',
    estimatedBudgetJpy: 15000,
    estimatedDurationMinutes: 90,
    tags: ['home', 'stationery', 'shopping'],
    external: {},
  },
  {
    id: 'ginza-loft',
    name: 'Ginza Loft',
    searchQuery: 'Ginza Loft Tokyo Japan',
    city: 'Tokyo',
    district: 'Ginza',
    category: 'shopping',
    priority: 'high',
    estimatedBudgetJpy: 12000,
    estimatedDurationMinutes: 90,
    tags: ['stationery', 'home', 'gifts'],
    external: {},
  },
  {
    id: 'ichiran-shibuya',
    name: 'Ichiran Shibuya',
    searchQuery: 'Ichiran Shibuya Tokyo Japan',
    city: 'Tokyo',
    district: 'Shibuya',
    category: 'restaurant',
    priority: 'must',
    estimatedBudgetJpy: 2000,
    estimatedDurationMinutes: 60,
    tags: ['ramen', 'food'],
    external: {},
  },
  {
    id: 'gyukatsu-motomura-shibuya',
    name: 'Gyukatsu Motomura',
    searchQuery: 'Gyukatsu Motomura Shibuya Tokyo Japan',
    city: 'Tokyo',
    district: 'Shibuya',
    category: 'restaurant',
    priority: 'must',
    estimatedBudgetJpy: 3000,
    estimatedDurationMinutes: 75,
    tags: ['beef', 'japanese-food'],
    external: {},
  },
  {
    id: 'uobei-shibuya',
    name: 'Uobei Shibuya',
    searchQuery: 'Uobei Shibuya Dogenzaka Tokyo Japan',
    city: 'Tokyo',
    district: 'Shibuya',
    category: 'restaurant',
    priority: 'high',
    estimatedBudgetJpy: 2500,
    estimatedDurationMinutes: 60,
    tags: ['sushi', 'food'],
    external: {},
  },
  {
    id: 'tokyo-disneyland',
    name: 'Tokyo Disneyland',
    searchQuery: 'Tokyo Disneyland Japan',
    city: 'Urayasu',
    category: 'park',
    priority: 'must',
    estimatedBudgetJpy: 15000,
    estimatedDurationMinutes: 720,
    tags: ['disney', 'theme-park'],
    external: {},
  },
  {
    id: 'tokyo-disneysea',
    name: 'Tokyo DisneySea',
    searchQuery: 'Tokyo DisneySea Japan',
    city: 'Urayasu',
    category: 'park',
    priority: 'must',
    estimatedBudgetJpy: 15000,
    estimatedDurationMinutes: 720,
    tags: ['disney', 'theme-park'],
    external: {},
  },
  {
    id: 'universal-studios-japan',
    name: 'Universal Studios Japan',
    searchQuery: 'Universal Studios Japan Osaka',
    city: 'Osaka',
    category: 'park',
    priority: 'must',
    estimatedBudgetJpy: 18000,
    estimatedDurationMinutes: 720,
    tags: ['universal', 'nintendo', 'theme-park'],
    external: {},
  },
]

export function getPlacesByCategory(category: PlaceCategory): Place[] {
  return places.filter((place) => place.category === category)
}
